In [14]:
import numpy as np

In [20]:
a=np.ones((4,4))
a


array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [21]:
a+1

array([[ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.]])

In [63]:
a=np.ones((4,4))
a[3,2] = 8
a[0,0] = 8
print(a)
for i in range(0,4):
        for j in range(0,4):
            if(a[i,j]==8):
                a[i,j]+=1

a

[[ 8.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  8.  1.]]


array([[ 9.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  9.,  1.]])

In [67]:
a=np.ones((4,4))
a[3,2] = 8
a[0,0] = 8
print(a)
for i in a:
        for j in i:
            if(j==8):
                j+=1

a

[[ 8.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  8.  1.]]


array([[ 8.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  8.,  1.]])

In [80]:
a=np.ones((4,4))
a[3,2] = 8
a[0,0] = 8
j for j in a if j==8
    j+=1

SyntaxError: invalid syntax (<ipython-input-80-076f7e403092>, line 4)

In [103]:
a=np.ones((4,4))
a[3,2] = 8
a[0,0] = 8
gen = ([x for x in y if x ==8] for y in a)
for x in gen:
    print(x)

[8.0]
[]
[]
[8.0]


In [105]:
a=np.ones((4,4))
a[3,2] = 8
a[0,0] = 8


In [110]:
a=np.ones((4,4))
a[3,2] = 8
a[0,0] = 8
b = map(lambda x:x=-1,&a)

b

SyntaxError: lambda cannot contain assignment (<ipython-input-110-9175b19c22d9>, line 4)